# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodFeed' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoodFeed
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
  
  target 'FoodFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
